language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4

env:
    global:
        - PIP_WHEEL_COMMAND="pip install --find-links http://wheels.astropy.org/ --use-wheel"

before_install:

    # Use utf8 encoding. Should be default, but this is insurance against
    # future changes
    - export PYTHONIOENCODING=UTF8

    # Install the pip that supports wheel
    - pip install setuptools --upgrade
    - pip install pip --upgrade
    - pip install wheel

install:
    - $PIP_WHEEL_COMMAND "pytest"
    - $PIP_WHEEL_COMMAND "Sphinx"
    - $PIP_WHEEL_COMMAND "pytest-cov"
    - $PIP_WHEEL_COMMAND "coveralls"

before_script:
    # Some of the tests use git commands that require a user to be configured
    - git config --global user.name "A U Thor"
    - git config --global user.email "author@example.com"

script:
    - py.test

after_success:
    - coveralls
